@startuml
' ======= layout =========
skinparam backgroundColor #fcf9ea
skinparam titleBorderRoundCorner 15
skinparam titleFontSize 30
skinparam classAttributeIconSize 0
skinparam titleFontName Arial Black
skinparam titleFontColor #f8a978
skinparam roundcorner 20
skinparam stereotypeCBackgroundColor ffc5a1
skinparam class {

ArrowColor ffc5a1
BorderColor White
BackgroundColor badfdb
}

' ======= title =========
center header


<font color=Black size=15><b>Built by WeByte ©</font>
endheader
title <b>SYSTEM SEQUENCE DIAGRAM\n
autonumber
'hide footbox
actor "Clinical Chemistry Technologist" as clinicalChemistryTechnologist

participant ":System" as System

activate clinicalChemistryTechnologist
activate System
clinicalChemistryTechnologist -> System : starts recording new test results
System --> clinicalChemistryTechnologist : request data (barcode)
deactivate System
clinicalChemistryTechnologist -> System : types requested data
activate System
System --> clinicalChemistryTechnologist : shows the test associated with the sample's barcode
deactivate System
loop for each parameter test
System --> clinicalChemistryTechnologist : asks for test parameter
activate System
clinicalChemistryTechnologist -> System : selects test parameter

System --> clinicalChemistryTechnologist : request the result value and metric
deactivate System
clinicalChemistryTechnologist -> System : types requested data
activate System
System --> clinicalChemistryTechnologist : informs operation success
deactivate System
end

@enduml
