@startuml
'https://plantuml.com/sequence-diagram
' ======= layout =========
skinparam backgroundColor #fcf9ea
skinparam titleBorderRoundCorner 15
skinparam titleFontSize 30
skinparam classAttributeIconSize 0
skinparam titleFontName Arial Black
skinparam titleFontColor #f8a978
skinparam roundcorner 20
skinparam stereotypeCBackgroundColor ffc5a1
skinparam class {

ArrowColor ffc5a1
BorderColor White
BackgroundColor badfdb
}


' ======= title =========
center header


<font color=Black size=15><b>Built by WeByte ©</font>
endheader
title <b>US8 - System Sequence Diagram\n

autonumber

actor ":Administrator" as Administrator
participant ":System" as System

activate Administrator


Administrator -> System: Starts  the creation of a new clinical analysis laboratory
 activate System

Administrator <-- System: Shows all tests and ask to select some of them.
deactivate System
loop while !allTestsSelected
Administrator -> System: selects the tests.
activate System
end



Administrator <-- System: Request data (name of clinic, ID, address, phone number, TIN)

deactivate System

Administrator -> System: Types the requested data.

activate System
System --> Administrator : Shows all the data and requests a confirmation
deactivate System


Administrator -> System : confirms the data

activate System
System --> Administrator : informs operation success
@enduml