@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Administrator as admin
participant ":System" as system
activate admin
admin -> system: starts the creation of the report to send to NHS.
activate system
system -> admin: asks to select the current day.
deactivate system

admin -> system: selects the current day
activate system
system -> admin: asks to select to send the day or week data to NHS.
deactivate system

admin -> system: selects to send the day/week data to NHS.
activate system
system -> admin: asks to introduce the number of historical points to send to NHS.
deactivate system
admin -> system: types the number of historical points to send to NHS.
activate system
system -> admin: asks to define the interval of days to fit the model.
deactivate system
admin -> system: selects the interval of days to fit the model.
activate system
system -> admin: asks to select the regression model to use.

deactivate system
admin -> system: selects the linear regression model to use.
alt simple linear regression model was selected

activate system
system -> admin: asks to select the independent variable

deactivate system
admin -> system: selects the independent variable.
activate system
end
system -> admin: asks to  introduce the significance level for hypothesis tests.
deactivate system

admin -> system: types the significance level
activate system
system -> admin:  asks to  introduce the significance level for confidence intervals.
deactivate system

admin -> system: types the significance level
activate system
system -> admin: shows all the data ans asks for a confirmation.
deactivate system
admin -> system: confirms all the data.
activate system
system -> admin: informs operation success.
@enduml1